eventHandler:
  architectures: arm64
  handler: src/handlers/sqs/dueDateTenantEventHandler.handleEventMessage
  timeout: 900
  events:
  - sqs:
      arn:
        Fn::GetAtt:
          - DueDateEventQueue
          - Arn
  tags:
    DEPARTMENT: k8cluster
    EMAIL: amit.kshirsagar.13@gmail.com