tenantHandler:
  handler: handlers/cron/tenantHandler.runCron
  timeout: 900
  # Invoke Lambda function every 2nd minute from Mon-Fri
  events:
    - schedule: cron(*/2 * * * ? *)

  tags:
    DEPARTMENT: DMS
    EMAIL: amit.kshirsagar@siemens.com